export { default as ClassDashboardClient } from './ClassDashboardClient';
export * from './ClassDashboardClient';
export { default as ClassHero } from './ClassHero';
export * from './ClassHero';
export { default as ClassTabs } from './ClassTabs';
export * from './ClassTabs';
export { default as TabContent } from './TabContent';
export * from './TabContent';
export { default as UploadMaterialButton } from './UploadMaterialButton';
export * from './UploadMaterialButton';
export { default as UploadMaterialModal } from './UploadMaterialModal';
export * from './UploadMaterialModal';
