/**
 * ACCESSIBILITY PAGE DATA
 */

export const ACCESSIBILITY_SECTIONS = [
  {
    title: "Our Commitment",
    paragraphs: [
      "Class Pilot is committed to ensuring that our platform is accessible to people with disabilities. We believe that every teacher and student deserves equal access to the tools they need to teach and learn effectively.",
      "We aim to conform to the [Web Content Accessibility Guidelines (WCAG) 2.1](https://www.w3.org/WAI/standards-guidelines/wcag/) at Level AA. This is an ongoing effort — we are actively working to improve the accessibility of all areas of the platform.",
    ],
  },
  {
    title: "What We've Done",
    intro: "The following accessibility measures are currently in place across Class Pilot:",
    list: [
      "**Keyboard navigation:** All interactive elements — buttons, links, form fields, and modals — are reachable and operable via keyboard alone",
      "**Screen reader support:** We use semantic HTML and ARIA labels throughout the interface to ensure compatibility with screen readers such as NVDA, JAWS, and VoiceOver",
      "**Colour contrast:** Text and UI elements meet or exceed WCAG AA contrast ratio requirements (4.5:1 for normal text, 3:1 for large text)",
      "**Focus indicators:** Visible focus outlines are present on all interactive elements so keyboard users can track their position on the page",
      "**Responsive design:** The platform works at all screen sizes and supports browser zoom up to 200% without loss of content or functionality",
      "**Alternative text:** All meaningful images include descriptive alt text. Decorative images are marked as presentational",
      "**Form labels:** All form inputs have associated labels and clear error messages",
      "**Consistent navigation:** Navigation menus and page structure are consistent and predictable across the platform",
    ],
  },
  {
    title: "Known Limitations",
    intro: "While we strive for full WCAG 2.1 AA compliance, there are some areas we are still working to improve:",
    list: [
      "**AI-generated content:** Feedback and answers generated by our AI features may occasionally use formatting that is not fully optimised for screen readers. We are working to improve how AI output is structured and announced.",
      "**Rich text editor:** The assignment submission editor has limited screen reader support in some browsers. A plain text fallback is available for all submissions.",
      "**PDF attachments:** PDFs uploaded by teachers are not automatically made accessible. We recommend teachers upload accessible PDFs where possible.",
    ],
    footer: "We are actively working on all of the above and aim to address them in upcoming releases.",
  },
  {
    title: "Supported Assistive Technologies",
    intro: "Class Pilot has been tested with the following assistive technologies:",
    list: [
      "NVDA with Chrome (Windows)",
      "JAWS with Chrome and Edge (Windows)",
      "VoiceOver with Safari (macOS and iOS)",
      "TalkBack with Chrome (Android)",
    ],
    footer: "We also support high-contrast mode in Windows and the Increased Contrast accessibility setting on macOS and iOS.",
  },
  {
    title: "Tips for Better Accessibility",
    intro: "You can adjust your experience using built-in browser and operating system settings:",
    list: [
      "**Increase text size:** Use your browser's zoom (Ctrl/Cmd +) or your operating system's accessibility text size settings",
      "**High contrast:** Enable high contrast mode in your OS settings — Class Pilot respects system-level contrast preferences",
      "**Reduce motion:** If you prefer reduced motion, enable the \"Reduce Motion\" setting on your device — our animations will be disabled automatically",
      "**Keyboard shortcuts:** Press `Tab` to move between elements and `Enter` or `Space` to activate buttons",
    ],
  },
];
